name: 'nvm-tools'
description: 'Local Nevermined development cluster'
inputs:
  token:
    description: 'Github personal access token with access to private nevermined-io organization repos'
    required: true
  contracts-version:
    description: 'Contracts version to use'
    required: false
    default: 'latest'
  node-version:
    description: 'The version of the node'
    required: false
    default: 'latest'
  marketplace-version:
    description: 'The marketplace api version'
    required: false
    default: 'latest'
  node:
    description: 'Start with node'
    required: false
    default: 'true'
  marketplace:
    description: 'Start with marketplace'
    required: false
    default: 'true'
  opengsn:
    description: 'Start with opengsn'
    required: false
    default: 'false'
  estuary:
    description: 'Start with estuary'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Install minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/v1.28.0/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
      shell: bash

    - name: Install argocd cli
      run: |
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/v2.5.3/argocd-linux-amd64
        sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
      shell: bash

    - uses: actions/checkout@v3
      with:
        repository: nevermined-io/nvm-tools
        path: nvm-tools
        token: ${{ inputs.token }}

    - name: 'Start nvm-tools'
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        CONTRACTS_VERSION: ${{ inputs.contracts-version }}
        NODE_VERSION: ${{ inputs.node-version }}
        MARKETPLACE_VERSION: ${{ inputs.marketplace-version }}
      working-directory: ./nvm-tools
      run: |
        ./nvm-tools start \
          $( [[ ${{ inputs.node }} == "false" ]] && printf %s '--no-node' ) \
          $( [[ ${{ inputs.marketplace }} == "false" ]] && printf %s '--no-marketplace' ) \
          $( [[ ${{ inputs.opengsn }} == "true" ]] && printf %s '--opengsn' ) \
          $( [[ ${{ inputs.estuary }} == "true" ]] && printf %s '--estuary' )
        sudo ln -s $PWD/nvm-tools /usr/local/bin
      shell: bash




