name: Testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          opengsn: "true"
          estuary: "true"
          compute: "true"

      - name: Test action artifacts
        run: |
          nvm-tools copy-artifacts ./artifacts
          ls -l ./artifacts/ready

      - name: Test action services
        run: |
          curl argocd.nevermined.localnet
          curl contracts.nevermined.localnet
          curl node.nevermined.localnet
          curl marketplace.nevermined.localnet
          curl opengsn.nevermined.localnet/getaddr
          curl estuary.nevermined.localnet/health
          curl argo.nevermined.localnet
          curl minio.nevermined.localnet